id = "shhhed-theme"
name = "shhhed"
version = "1.33.7"
schema_version = 1
authors = ["mkhamat"]
description = "🤫 Dark theme that dims the scaffolding and colors what matters."
repository = "https://github.com/mkhamat/shhhed"
